#+title: jinx.el - Changelog
#+author: Daniel Mendler
#+language: en

* Development

- =jinx-correct=: Consistently move backward to the previous misspelling. In order
  to move backward further, press =M-$= again (or =M-p=). Move forward with =M-n=.
- =jinx-correct-select=: Support more than 10 quick keys.
- Add =jinx-faces= customization group.

* Version 0.7 (2023-04-21)

- Bugfixes
- =jinx-languages=: Only ask in file-backed buffers if file-local variable should
  be saved.
- Push =undo-boundary= before correcting a word, such that corrections are not
  undone in a single step.
- =jinx-correct=: Use =+= as prefix to add word to the current session.
- Add =jinx-correct-map= bound in the =jinx-correct= minibuffer.
- Add navigation keys to correction UI. The commands =jinx-correct-next= and
  =jinx-correct-previous= are bound to the keys =M-n= and =M-p= in the
  =jinx-correct-map= respectively. The commands accept prefix arguments to skip
  over a number of misspellings.
- Add quick selection keys to correction UI. The command =jinx-correct-select= is
  bound to the keys =1= to =9= in the =jinx-correct-map=.
- Try to locate the native module =jinx-mod.so= first on the =load-path= before
  attempting to compile it. This is useful if the module is packed and installed
  separately.

* Version 0.6 (2023-04-17)

- Fix the type of a few characters: =.= punctuation character, ='= word character, =%=
  and =$= identifier characters.
- Abandon =flyspell-mode-predicate= completely. Rely on faces only.
- =jinx-languages=: The value must be a string now. Multiple language codes can be
  separated by space.
- =jinx-languages=: Ask if the file-local variable should be saved when changing
  the language.
- Add =jinx-local-words= to save file-local words. =jinx-correct= supports saving to
  =jinx-local-words= by pressing =*=.
- Add a lighter and a minor mode menu.
- Avoid scheduling the idle timer while typing a word.

* Version 0.5 (2023-04-05)

- Add =jinx-languages= command to switch languages locally or globally.
- =jinx-correct=: When checking the whole buffer via =C-u M-$=, don't restore
  original point position upon =C-g= to ease cursory edits. Instead push a mark
  which can be used to go back to the original position.
- Add =jinx-mode-map= to make it easy to bind keys if =jinx-mode= is enabled. The
  map is empty by default.
- Ignore single quotes and apostrophes at the beginning and end of words. Please
  provide feedback if this is a reasonable approach.
- Support spell checking of camelCased words via the =jinx-camel-modes= variable.

* Version 0.4 (2023-03-27)

- =jinx-languages=: Fall back to =$LANG= environment variable, since
  =current-locale-environment= is an Emacs 29 addition.
- =jinx--mod-wordchars=: Handle non-UTF8 return values gracefully.
- =jinx-correct=: Always start from nearest overlay.
- =jinx-misspelled=: Use less obtrusive color for the underlining.

* Version 0.3 (2023-03-27)

- Add =jinx-misspelled-map=.
- =jinx-correct=: Unfold invisible line when correcting misspellings.
- =jinx-correct=: Show number of misspellings.
- Add =emacs-module.h= to avoid compilation problems.
- =jinx-languages=: Use =current-locale-environment= by default.

* Version 0.2 (2023-03-26)

- Start of changelog.
